#!/bin/bash
chmod -x 22-users_and_homes 21-reverse 20-hiago  19-AZ 18-letteronly 17-hidethisword 16-whatsnext
15-countthatword 14-findthatword 13-unique 12-newest_files 11-directories 10-no_more_js 9-duplicate_last_line 
 8-cwd_state 7-file 6-third_line 5-firstlines 4-lastlines 3-twofiles 2-hellofile 1-confused_smiley 0-hello_world