#!/usr/bin/env bash
# Transfers a file from our client to a server:
# Accepts four arguments:
#+    The path to the file to be transferred.
#+    The IP of the server to transfer the file to.
#+    The username that scp connects with.
#+    The path to the SSH private key that scp uses.

# Check if the correct number of arguments are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Transfer file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~

# Check if scp command was successful
if [ $? -eq 0 ]; then
    echo "File transfer successful"
else
    echo "File transfer failed"
fi

