#!/usr/bin/env bash
#creat the PID file

echo $$ > /var/run/myscript.pid

while true;
do
    echo "To infinity and beyond"
    sleep 1
done

trap "I hate the kill command"  SIGTERM
trap "Y U no love me?!" SIGINT
trap "rm /var/run/myscript.pid; exit" SIGQUIT SIGTERM

