#!/usr/bin/env bash
#a Bash script that displays the PID, along with the process name, of processes 
for pid in /proc/*/status;
do
    if grep -q "Name:.*bash" "$pid";
    then
        awk '/^Pid/{pid=$2} /^Name/{name=$2} END{print pid, name}' "$pid"
    fi
done

