#!/usr/bin/env bash
# This script is displaying In a list format
for i in {1..100}
do
    if ((i % 3 == 0)) && ((i % 5 == 0))
    then
        echo "FizzBuzz"
    elif ((i % 3 == 0))
    then
        echo "Fizz"
    elif ((i % 5 == 0))
    then
        echo "Buzz"
    else
        echo "$i"
    fi
done

