#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
for i in {0..10}
do 
    
    if ((i == 4))
    then
        echo "bad luck"
    elif ((i == 8))
    then
        echo "good luck"
    else
        echo "Best School"
    fi
done

