#!/usr/bin/env bash
# This script is displaying 1 - 20 times
i=0
while (($i <= 20))
do 
    
    if ((i == 4))
    then
        echo "bad luck from China"
    elif ((i == 9))
    then
        echo "bad luck from Japan"
    elif ((i == 17))
    then
        echo "bad luck from Italy"
    else
        echo $i
    fi
    i=`expr $i + 1`
done

