#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:
hour=0
echo "Hour: $hour"
while [ $hour -lt 12 ]
do
    minute=1
    while [ $minute -lt 60 ]
    do
        echo "$minute"
        minute=$((minute+1))
    done
    echo "Hour: $hour"
    hour=$((hour+1))
done
 
        