#!/usr/bin/env bash
# This script is displaying In a list format
file="school"

if [ -e school ]
then
    echo "school file exists"
    if [ -s school ]
    then
        echo "shool file is not empty"
    else
        echo "shool file is empty"
    fi
    if [ -f school ]
    then
        echo "school is a regular file"
    fi
    else
        echo "school file does not exist"
    fi

